name: Publish ELIZA Chatbot

on:
  push:
    branches:
      - main

jobs:
  deploy-chatbot:
    runs-on: ubuntu-latest

    steps:
      - name: Clone the Repository
        uses: actions/checkout@v3

      - name: Configure Deployment Environment
        run: echo "Preparing deployment to GitHub Pages..."

      - name: Verify Deployment Files
        run: |
          if [ ! -d "./eliza" ]; then
            echo "Error: The 'eliza' directory does not exist. Aborting deployment."
            exit 1
          fi

      - name: Deploy Chatbot to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./eliza
